"""Literal meanings shared by rendered initial states and English rules."""

VOCABULARY = {
    "blocks": {
        "clear": "{0} rests on the table or another block and has nothing on top",
        "on_table": "{0} is on the table",
        "arm_empty": "the arm is empty",
        "holding": "the arm holds {0}",
        "on": "{0} is directly on {1}",
    },
    "hanoi": {
        "clear": "{0} has nothing on top",
        "on": "{0} is directly on {1}",
        "smaller": "{0} may support {1}: it is a larger disk or a peg",
    },
    "sliding_puzzle": {
        "at": "tile {0} is at cell {1}",
        "neighbor": "cell {0} is orthogonally adjacent to cell {1}",
        "empty": "cell {0} is the blank",
    },
    "gripper": {
        "at_robby": "the robot is in room {0}",
        "at": "ball {0} rests in room {1} outside both grippers",
        "free": "gripper {0} is empty",
        "carry": "gripper {1} holds ball {0}",
    },
    "miconic": {
        "origin": "passenger {0} starts at floor {1}",
        "destin": "passenger {0} needs floor {1}",
        "above": "floor {1} is above floor {0}",
        "boarded": "passenger {0} is in the lift",
        "not_boarded": "passenger {0} is outside the lift",
        "served": "passenger {0} has been delivered",
        "not_served": "passenger {0} has not been delivered",
        "lift_at": "the lift is at floor {0}",
    },
    "floortile": {
        "robot_at": "robot {0} is at tile {1}",
        "up": "tile {0} is immediately above tile {1}",
        "down": "tile {0} is immediately below tile {1}",
        "right": "tile {0} is immediately right of tile {1}",
        "left": "tile {0} is immediately left of tile {1}",
        "clear": "tile {0} is unpainted and unoccupied",
        "painted": "tile {0} is painted {1}",
        "robot_has": "robot {0} uses paint colour {1}",
        "available_color": "paint colour {0} is available",
        "free_color": "robot {0} may change its paint colour",
    },
    "termes": {
        "height": "cell {0} has height {1}",
        "at": "the robot is at cell {0}",
        "has_block": "the robot carries one block",
        "succ": "height {0} is exactly one above height {1}",
        "neighbor": "cell {0} is orthogonally adjacent to cell {1}",
        "is_depot": "cell {0} is a block depot",
    },
    "freecell": {
        "on": "card {0} lies directly on card {1} in a tableau column",
        "incell": "card {0} occupies a freecell",
        "clear": "card {0} is the exposed top of a tableau column",
        "cellspace": "there are {0} empty freecells",
        "colspace": "there are {0} empty columns",
        "home": "card {0} is the top of its foundation",
        "bottomcol": "card {0} is at the bottom of a tableau column",
        "canstack": "card {0} may be placed on card {1} according to rank and alternating colour",
        "hassuit": "card {0} has suit {1}",
        "value": "card {0} has rank {1}",
        "successor": "rank {0} is exactly one above rank {1}",
        "colsuccessor": "empty-column count {0} is exactly one above {1}",
        "cellsuccessor": "empty-freecell count {0} is exactly one above {1}",
    },
    "briefcase": {
        "at": "item {0} is at location {1}",
        "in": "item {0} is inside the briefcase",
        "is_at": "the briefcase is at location {0}",
    },
}
